name: Count Lines of Code

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default credentials so our push action uses its own token

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Run cloc and save output
        run: |
          echo "Lines of Code Report - $(date)" > cloc_report.txt
          cloc . --exclude-dir=node_modules,dist,coverage,.devcontainer >> cloc_report.txt
          echo "" >> cloc_report.txt
          echo "Generated on: $(date)" >> cloc_report.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cloc_report.txt
          # Commit only if there are changes; if none, don't error out
          git commit -m "Update cloc report [$(date)]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
